name: "FTP to Telegram"
version: "1.0.2"
slug: "ftp_to_telegram"
description: "LÃ¤dt Videos vom FTP und sendet sie an Telegram."
startup: services
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - "config:rw"
host_network: true
options:
  ftp_host: ""
  ftp_user: ""
  ftp_pass: ""
  ftp_port: 21
  bot_token: ""
  chat_id: ""
  target_fps: 30
  delete_after_success: false
schema:
  ftp_host: str
  ftp_user: str
  ftp_pass: password
  ftp_port: int
  bot_token: password
  chat_id: str
  target_fps: int
  delete_after_success: bool